HelloWorld:
    resource: ../../src/HelloWorld/Controller/
    type: annotation

Blog:
    resource: ../../src/Blog/Controller/
    type: annotation

Customers:
    resource: ../../src/Customers/Controller/
    type: annotation

Security:
    resource: ../../src/Security/Controller/
    type: annotation
